server:
  port: 8084


spring:
    datasource:
        name: test
        url: jdbc:mysql://rm-2ze6bugd0e59jl0ibo.mysql.rds.aliyuncs.com:3306/tvm_qr_purchase?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: founder_123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20
   

redis:
      host: localhost
      port: 6379
      password:
      # 连接超时时间（毫秒）
      timeout: 10000
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1

spring.profiles.active: dev 
logging.level.org.springframework.web: debug 


mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.core.model

mapper:
  mappers:  com.core.dao
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

#热部署生效
spring.devtools.restart.enabled: true
#设置重启的目录
#spring.devtools.restart.additional-paths: src/main/java
#classpath目录下的WEB-INF文件夹内容修改不重启
spring.devtools.restart.exclude: WEB-INF/**
   
   
# 定位模板的目录
spring.mvc.view.prefix: classpath:/templates/
# 给返回的页面添加后缀名
spring.mvc.view.suffix: .html

#ssl证书配置
#server.port: 443
#server.ssl.key-store: classpath:1529678010187.pfx
#server.ssl.key-store-password: 1529678010187
#server.ssl.keyStoreType: PKCS12